name: walletdz
description: "A new Wallet project For Ain EL Turck."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-26.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.1
  firebase_messaging: ^15.1.1
  firebase_database: ^11.1.2
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_storage: any
  firebase_in_app_messaging: ^0.8.0+6
  firebase_analytics: any
  google_sign_in: ^6.2.1
  cached_network_image: any
  lottie: any
  provider: ^6.1.2
  fluttertoast: any
  font_awesome_flutter: ^10.7.0
  #  flutter_native_splash: any
  shared_preferences: ^2.3.2
  avatar_glow: ^3.0.1
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  intl: ^0.19.0
#  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.2.3
  ticket_widget: ^1.0.2
  readmore: ^3.0.0
  #  flutterflow_paginate_firestore: ^1.0.3+1
  dart_date: ^1.4.0
  flutter_staggered_grid_view: ^0.7.0
  #  calendar_timeline: ^1.0.5
  shimmer: ^3.0.0
  rename: ^3.0.2
  marquee: ^2.2.3
  screenshot: ^3.0.0
  email_validator: ^3.0.0
  flutter_islamic_icons: ^1.0.2
  supabase_flutter: ^2.6.0
  #  horizontal_calendar: any
  geocoding: ^3.0.0
  map_launcher: any
  open_location_picker: ^1.1.0
  jiffy: any
  google_fonts: ^6.2.1
  googleapis_auth:
#  sqflite: ^2.3.3+1
  path: ^1.9.0
  timelines: ^0.1.0
  animated_flip_counter: ^0.3.4
  pretty_qr_code: ^3.3.0
  http: ^1.2.2
  decimal: ^3.0.2
#  openfoodfacts: ^3.14.0
  video_player: ^2.9.1
  chewie: ^1.8.5
  flutter_easyloading: ^3.0.5
  wakelock_plus: ^1.2.8
  faker: ^2.2.0
  postgres: ^3.3.0
  timeago: ^3.7.0
#  sqflite_common_ffi: ^2.3.3
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
#  flutter_slidable: ^3.1.1
  network_info_plus: ^6.0.1
  multicast_dns: ^0.3.2+7
  percent_indicator: ^4.2.3
  icons_plus: ^5.0.0
  feedback: ^3.1.0
  win32: ^5.5.4
  msix: ^3.16.8
  easy_date_timeline: ^1.1.3
  device_info_plus: any
  pincode_input_fields: ^1.0.3
  syncfusion_flutter_barcodes: ^26.2.14
  excel: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  objectbox_generator: ^4.0.2
  build_runner: ^2.4.12


flutter_icons:
  android: true
  ios: true
  #  image_path: "assets/images/dolphin-emoji.png"
  image_path: "assets/images/ic_launcher/1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ic_launcher/1024.png"
    #    image_path: "assets/images/ic_launcher/1024.png"
    adaptive_icon_foreground: "assets/images/ic_launcher/1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ic_launcher/1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ic_launcher/1024.png"

flutter_native_splash:
  color: "#ffffff"
  image : assets/splash2.png
  #  image: assets/images/ic_launcher/1024.png

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true



  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald-SemiBold.ttf
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Light.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
    - family: ArbFONTS
      fonts:
        - asset: assets/fonts/ArbFONTS-khalaad-al-arabeh.ttf
  #        - asset: assets/fonts/NizarBBCKurdish-Bold.ttf

  assets:
    - assets/
    - assets/lotties/
    - assets/images/ic_launcher/1024.png
    - assets/images/744878.png
    - assets/images/icon.png
    - assets/firebase_logo.png
    - assets/google_logo.png


