// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxAY36yIKV40uJK2MPo8WhW_xi4DAFN0k',
    appId: '1:330293988254:web:dc6a9fd6b5fed04f41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    authDomain: 'walletdz-d12e0.firebaseapp.com',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    measurementId: 'G-B0CPTM2YT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeLnEzq0iSZjfx0R-pgu6cs89Ooyfozq0',
    appId: '1:330293988254:android:61adcf051c6c384c41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAie3hehD-yr_4tOGx0u94JjZL-i16-ROA',
    appId: '1:330293988254:ios:e03eaa1385b7e75741648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    androidClientId: '330293988254-oipcq87lmch78m131nauh2b6c2fb0875.apps.googleusercontent.com',
    iosClientId: '330293988254-gfocd18j16kdnsvqhp1fk61ggr6ovp42.apps.googleusercontent.com',
    iosBundleId: 'com.wallet.dz.walletdz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAie3hehD-yr_4tOGx0u94JjZL-i16-ROA',
    appId: '1:330293988254:ios:e03eaa1385b7e75741648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    androidClientId: '330293988254-oipcq87lmch78m131nauh2b6c2fb0875.apps.googleusercontent.com',
    iosClientId: '330293988254-gfocd18j16kdnsvqhp1fk61ggr6ovp42.apps.googleusercontent.com',
    iosBundleId: 'com.wallet.dz.walletdz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxAY36yIKV40uJK2MPo8WhW_xi4DAFN0k',
    appId: '1:330293988254:web:6decef77298806bf41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    authDomain: 'walletdz-d12e0.firebaseapp.com',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    measurementId: 'G-4N0BTDFDXS',
  );

}