// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'objectBox/Entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1607491491677936871),
      name: 'Fournisseur',
      lastPropertyId: const obx_int.IdUid(10, 205619321565883428),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4128254359789025437),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8758188655905488373),
            name: 'qr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 414205311028485250),
            name: 'nom',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8919268741099517413),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7832871292473157035),
            name: 'adresse',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4341932180325338788),
            name: 'dateCreation',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 9088776954073551638),
            name: 'derniereModification',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5264206445168036661),
            name: 'createdBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6446406569798399453),
            name: 'updatedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 205619321565883428),
            name: 'deletedBy',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 2832941486252609678),
            name: 'produits',
            targetId: const obx_int.IdUid(2, 8606136097133066204))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8606136097133066204),
      name: 'Produit',
      lastPropertyId: const obx_int.IdUid(20, 5939741701584325095),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3899042760461107286),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1144798314351403869),
            name: 'qr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 257039154436617685),
            name: 'image',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8034655794147681628),
            name: 'nom',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9164585532905782971),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6533552764826989296),
            name: 'prixAchat',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8989117107807645988),
            name: 'prixVente',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4773469945258199278),
            name: 'stock',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3618662337063473621),
            name: 'stockUpdate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7598222863889683261),
            name: 'stockinit',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1827255615047715957),
            name: 'dateCreation',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 5341105790295986650),
            name: 'datePeremption',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5607971647867899978),
            name: 'derniereModification',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 8209867430423604798),
            name: 'minimStock',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 6070155937091833855),
            name: 'origine',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 78856214289649542),
            name: 'createdBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 2514304964873444278),
            name: 'updatedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 78600634238338283),
            name: 'deletedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 5939741701584325095),
            name: 'alertPeremption',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'approvisionnements',
            srcEntity: 'Approvisionnement',
            srcField: ''),
        obx_int.ModelBacklink(
            name: 'fournisseurs', srcEntity: 'Fournisseur', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7968206822164606643),
      name: 'Client',
      lastPropertyId: const obx_int.IdUid(12, 4584540760971899695),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3550449193447442136),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4262833269610261032),
            name: 'qr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 36313311528968912),
            name: 'nom',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3647177150120252920),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8510624876376955688),
            name: 'adresse',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7948986094101501762),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6863376831137326481),
            name: 'dateCreation',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4541506935688772376),
            name: 'derniereModification',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 789514639796378856),
            name: 'createdBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 8171432931510958161),
            name: 'updatedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4584540760971899695),
            name: 'deletedBy',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'factures', srcEntity: 'Facture', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 1285774936409385946),
      name: 'Facture',
      lastPropertyId: const obx_int.IdUid(8, 4377413958790530702),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 703887304841839968),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 142214021994294718),
            name: 'qr',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 807322010398501475),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7593775792342322389),
            name: 'clientId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 7209079759549609437),
            relationTarget: 'Client'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2789430178740285634),
            name: 'createdBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1404650867823199132),
            name: 'updatedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7595078940008474740),
            name: 'deletedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4377413958790530702),
            name: 'impayer',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'lignesFacture', srcEntity: 'LigneFacture', srcField: '')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 615909935097060499),
      name: 'LigneFacture',
      lastPropertyId: const obx_int.IdUid(5, 2176273511660132623),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7495577581902831294),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8662175227878512386),
            name: 'produitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 4469509526914219384),
            relationTarget: 'Produit'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2271720061750415984),
            name: 'factureId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 3115440698062349467),
            relationTarget: 'Facture'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3968408471191777871),
            name: 'quantite',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2176273511660132623),
            name: 'prixUnitaire',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 4476248726244800597),
      name: 'DeletedProduct',
      lastPropertyId: const obx_int.IdUid(9, 6711389730840919433),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7813442985589411931),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5897104726740693875),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3113702929616874283),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5134769009321365682),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5435292101446515439),
            name: 'quantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1036436451411558170),
            name: 'createdBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6987534803578766938),
            name: 'updatedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 880067361688206477),
            name: 'deletedBy',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6711389730840919433),
            name: 'deletedAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 4487301589449865946),
      name: 'User',
      lastPropertyId: const obx_int.IdUid(7, 8617873835436875934),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7502244617574886101),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4814196349563094451),
            name: 'photo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2646315751348335777),
            name: 'username',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3354385379024341747),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4292417183407275029),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3611056481111139689),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8617873835436875934),
            name: 'role',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 5406683045265354164),
      name: 'Approvisionnement',
      lastPropertyId: const obx_int.IdUid(6, 5704210873674130259),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1427127697992029180),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6586041333414819153),
            name: 'quantite',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8947335276371114795),
            name: 'prixUnitaire',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9010323130560500227),
            name: 'datePeremption',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5002393926981366444),
            name: 'produitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 8838837656771167107),
            relationTarget: 'Produit'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5704210873674130259),
            name: 'fournisseurId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 7561266591184972565),
            relationTarget: 'Fournisseur')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(9, 5406683045265354164),
      lastIndexId: const obx_int.IdUid(9, 7561266591184972565),
      lastRelationId: const obx_int.IdUid(1, 2832941486252609678),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [6647246884597588827],
      retiredIndexUids: const [7680843215305245682, 720122404314208774],
      retiredPropertyUids: const [
        8976483595831028651,
        8205124793224732825,
        4459084450102477862,
        2863238699579242918,
        6338489518372838743,
        9126168680358256829,
        7098507666294938412,
        4094610592500505256,
        2787760657972690405
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Fournisseur: obx_int.EntityDefinition<Fournisseur>(
        model: _entities[0],
        toOneRelations: (Fournisseur object) => [],
        toManyRelations: (Fournisseur object) => {
              obx_int.RelInfo<Fournisseur>.toMany(1, object.id): object.produits
            },
        getId: (Fournisseur object) => object.id,
        setId: (Fournisseur object, int id) {
          object.id = id;
        },
        objectToFB: (Fournisseur object, fb.Builder fbb) {
          final qrOffset =
              object.qr == null ? null : fbb.writeString(object.qr!);
          final nomOffset = fbb.writeString(object.nom);
          final phoneOffset =
              object.phone == null ? null : fbb.writeString(object.phone!);
          final adresseOffset =
              object.adresse == null ? null : fbb.writeString(object.adresse!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, qrOffset);
          fbb.addOffset(2, nomOffset);
          fbb.addOffset(3, phoneOffset);
          fbb.addOffset(4, adresseOffset);
          fbb.addInt64(5, object.dateCreation.millisecondsSinceEpoch);
          fbb.addInt64(6, object.derniereModification?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.createdBy);
          fbb.addInt64(8, object.updatedBy);
          fbb.addInt64(9, object.deletedBy);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final derniereModificationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final qrParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final nomParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final adresseParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final createdByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final updatedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final deletedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final dateCreationParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final derniereModificationParam = derniereModificationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(derniereModificationValue);
          final object = Fournisseur(
              id: idParam,
              qr: qrParam,
              nom: nomParam,
              phone: phoneParam,
              adresse: adresseParam,
              createdBy: createdByParam,
              updatedBy: updatedByParam,
              deletedBy: deletedByParam,
              dateCreation: dateCreationParam,
              derniereModification: derniereModificationParam);
          obx_int.InternalToManyAccess.setRelInfo<Fournisseur>(object.produits,
              store, obx_int.RelInfo<Fournisseur>.toMany(1, object.id));
          return object;
        }),
    Produit: obx_int.EntityDefinition<Produit>(
        model: _entities[1],
        toOneRelations: (Produit object) => [],
        toManyRelations: (Produit object) => {
              obx_int.RelInfo<Approvisionnement>.toOneBacklink(5, object.id,
                      (Approvisionnement srcObject) => srcObject.produit):
                  object.approvisionnements,
              obx_int.RelInfo<Fournisseur>.toManyBacklink(1, object.id):
                  object.fournisseurs
            },
        getId: (Produit object) => object.id,
        setId: (Produit object, int id) {
          object.id = id;
        },
        objectToFB: (Produit object, fb.Builder fbb) {
          final qrOffset =
              object.qr == null ? null : fbb.writeString(object.qr!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          final nomOffset = fbb.writeString(object.nom);
          final descriptionOffset = object.description == null
              ? null
              : fbb.writeString(object.description!);
          final origineOffset =
              object.origine == null ? null : fbb.writeString(object.origine!);
          fbb.startTable(21);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, qrOffset);
          fbb.addOffset(2, imageOffset);
          fbb.addOffset(3, nomOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addFloat64(5, object.prixAchat);
          fbb.addFloat64(6, object.prixVente);
          fbb.addFloat64(7, object.stock);
          fbb.addInt64(8, object.stockUpdate?.millisecondsSinceEpoch);
          fbb.addFloat64(10, object.stockinit);
          fbb.addInt64(11, object.dateCreation?.millisecondsSinceEpoch);
          fbb.addInt64(12, object.datePeremption?.millisecondsSinceEpoch);
          fbb.addInt64(13, object.derniereModification.millisecondsSinceEpoch);
          fbb.addFloat64(14, object.minimStock);
          fbb.addOffset(15, origineOffset);
          fbb.addInt64(16, object.createdBy);
          fbb.addInt64(17, object.updatedBy);
          fbb.addInt64(18, object.deletedBy);
          fbb.addInt64(19, object.alertPeremption);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final stockUpdateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final dateCreationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
          final datePeremptionValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final qrParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final imageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final nomParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final origineParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 34);
          final prixAchatParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final prixVenteParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final stockParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final minimStockParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 32, 0);
          final createdByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          final updatedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          final deletedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 40, 0);
          final alertPeremptionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 42, 0);
          final dateCreationParam = dateCreationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateCreationValue);
          final datePeremptionParam = datePeremptionValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(datePeremptionValue);
          final stockUpdateParam = stockUpdateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(stockUpdateValue);
          final derniereModificationParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0));
          final stockinitParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final object = Produit(
              id: idParam,
              qr: qrParam,
              image: imageParam,
              nom: nomParam,
              description: descriptionParam,
              origine: origineParam,
              prixAchat: prixAchatParam,
              prixVente: prixVenteParam,
              stock: stockParam,
              minimStock: minimStockParam,
              createdBy: createdByParam,
              updatedBy: updatedByParam,
              deletedBy: deletedByParam,
              alertPeremption: alertPeremptionParam,
              dateCreation: dateCreationParam,
              datePeremption: datePeremptionParam,
              stockUpdate: stockUpdateParam,
              derniereModification: derniereModificationParam,
              stockinit: stockinitParam);
          obx_int.InternalToManyAccess.setRelInfo<Produit>(
              object.approvisionnements,
              store,
              obx_int.RelInfo<Approvisionnement>.toOneBacklink(5, object.id,
                  (Approvisionnement srcObject) => srcObject.produit));
          obx_int.InternalToManyAccess.setRelInfo<Produit>(object.fournisseurs,
              store, obx_int.RelInfo<Fournisseur>.toManyBacklink(1, object.id));
          return object;
        }),
    Client: obx_int.EntityDefinition<Client>(
        model: _entities[2],
        toOneRelations: (Client object) => [],
        toManyRelations: (Client object) => {
              obx_int.RelInfo<Facture>.toOneBacklink(
                      4, object.id, (Facture srcObject) => srcObject.client):
                  object.factures
            },
        getId: (Client object) => object.id,
        setId: (Client object, int id) {
          object.id = id;
        },
        objectToFB: (Client object, fb.Builder fbb) {
          final qrOffset = fbb.writeString(object.qr);
          final nomOffset = fbb.writeString(object.nom);
          final phoneOffset = fbb.writeString(object.phone);
          final adresseOffset = fbb.writeString(object.adresse);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, qrOffset);
          fbb.addOffset(2, nomOffset);
          fbb.addOffset(3, phoneOffset);
          fbb.addOffset(4, adresseOffset);
          fbb.addOffset(5, descriptionOffset);
          fbb.addInt64(7, object.dateCreation?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.derniereModification?.millisecondsSinceEpoch);
          fbb.addInt64(9, object.createdBy);
          fbb.addInt64(10, object.updatedBy);
          fbb.addInt64(11, object.deletedBy);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateCreationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final derniereModificationValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final qrParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nomParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final adresseParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final createdByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final updatedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final deletedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final dateCreationParam = dateCreationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dateCreationValue);
          final derniereModificationParam = derniereModificationValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(derniereModificationValue);
          final object = Client(
              id: idParam,
              qr: qrParam,
              nom: nomParam,
              phone: phoneParam,
              adresse: adresseParam,
              description: descriptionParam,
              createdBy: createdByParam,
              updatedBy: updatedByParam,
              deletedBy: deletedByParam,
              dateCreation: dateCreationParam,
              derniereModification: derniereModificationParam);
          obx_int.InternalToManyAccess.setRelInfo<Client>(
              object.factures,
              store,
              obx_int.RelInfo<Facture>.toOneBacklink(
                  4, object.id, (Facture srcObject) => srcObject.client));
          return object;
        }),
    Facture: obx_int.EntityDefinition<Facture>(
        model: _entities[3],
        toOneRelations: (Facture object) => [object.client],
        toManyRelations: (Facture object) => {
              obx_int.RelInfo<LigneFacture>.toOneBacklink(3, object.id,
                      (LigneFacture srcObject) => srcObject.facture):
                  object.lignesFacture
            },
        getId: (Facture object) => object.id,
        setId: (Facture object, int id) {
          object.id = id;
        },
        objectToFB: (Facture object, fb.Builder fbb) {
          final qrOffset = fbb.writeString(object.qr);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, qrOffset);
          fbb.addInt64(2, object.date.millisecondsSinceEpoch);
          fbb.addInt64(3, object.client.targetId);
          fbb.addInt64(4, object.createdBy);
          fbb.addInt64(5, object.updatedBy);
          fbb.addInt64(6, object.deletedBy);
          fbb.addFloat64(7, object.impayer);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final qrParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final impayerParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 18);
          final createdByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final updatedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final deletedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = Facture(
              id: idParam,
              date: dateParam,
              qr: qrParam,
              impayer: impayerParam,
              createdBy: createdByParam,
              updatedBy: updatedByParam,
              deletedBy: deletedByParam);
          object.client.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.client.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Facture>(
              object.lignesFacture,
              store,
              obx_int.RelInfo<LigneFacture>.toOneBacklink(
                  3, object.id, (LigneFacture srcObject) => srcObject.facture));
          return object;
        }),
    LigneFacture: obx_int.EntityDefinition<LigneFacture>(
        model: _entities[4],
        toOneRelations: (LigneFacture object) =>
            [object.produit, object.facture],
        toManyRelations: (LigneFacture object) => {},
        getId: (LigneFacture object) => object.id,
        setId: (LigneFacture object, int id) {
          object.id = id;
        },
        objectToFB: (LigneFacture object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.produit.targetId);
          fbb.addInt64(2, object.facture.targetId);
          fbb.addFloat64(3, object.quantite);
          fbb.addFloat64(4, object.prixUnitaire);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final quantiteParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final prixUnitaireParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = LigneFacture(
              id: idParam,
              quantite: quantiteParam,
              prixUnitaire: prixUnitaireParam);
          object.produit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.produit.attach(store);
          object.facture.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.facture.attach(store);
          return object;
        }),
    DeletedProduct: obx_int.EntityDefinition<DeletedProduct>(
        model: _entities[5],
        toOneRelations: (DeletedProduct object) => [],
        toManyRelations: (DeletedProduct object) => {},
        getId: (DeletedProduct object) => object.id,
        setId: (DeletedProduct object, int id) {
          object.id = id;
        },
        objectToFB: (DeletedProduct object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addFloat64(3, object.price);
          fbb.addInt64(4, object.quantity);
          fbb.addInt64(5, object.createdBy);
          fbb.addInt64(6, object.updatedBy);
          fbb.addInt64(7, object.deletedBy);
          fbb.addInt64(8, object.deletedAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final quantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final deletedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0));
          final createdByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final updatedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final deletedByParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final object = DeletedProduct(
              name: nameParam,
              description: descriptionParam,
              price: priceParam,
              quantity: quantityParam,
              deletedAt: deletedAtParam,
              createdBy: createdByParam,
              updatedBy: updatedByParam,
              deletedBy: deletedByParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    User: obx_int.EntityDefinition<User>(
        model: _entities[6],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final photoOffset =
              object.photo == null ? null : fbb.writeString(object.photo!);
          final usernameOffset = fbb.writeString(object.username);
          final passwordOffset = fbb.writeString(object.password);
          final emailOffset = fbb.writeString(object.email);
          final phoneOffset =
              object.phone == null ? null : fbb.writeString(object.phone!);
          final roleOffset = fbb.writeString(object.role);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, photoOffset);
          fbb.addOffset(2, usernameOffset);
          fbb.addOffset(3, passwordOffset);
          fbb.addOffset(4, emailOffset);
          fbb.addOffset(5, phoneOffset);
          fbb.addOffset(6, roleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final photoParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final usernameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final roleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = User(
              id: idParam,
              photo: photoParam,
              username: usernameParam,
              password: passwordParam,
              phone: phoneParam,
              email: emailParam,
              role: roleParam);

          return object;
        }),
    Approvisionnement: obx_int.EntityDefinition<Approvisionnement>(
        model: _entities[7],
        toOneRelations: (Approvisionnement object) =>
            [object.produit, object.fournisseur],
        toManyRelations: (Approvisionnement object) => {},
        getId: (Approvisionnement object) => object.id,
        setId: (Approvisionnement object, int id) {
          object.id = id;
        },
        objectToFB: (Approvisionnement object, fb.Builder fbb) {
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.quantite);
          fbb.addFloat64(2, object.prixUnitaire);
          fbb.addInt64(3, object.datePeremption?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.produit.targetId);
          fbb.addInt64(5, object.fournisseur.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final datePeremptionValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final quantiteParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final prixUnitaireParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final datePeremptionParam = datePeremptionValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(datePeremptionValue);
          final object = Approvisionnement(
              id: idParam,
              quantite: quantiteParam,
              prixUnitaire: prixUnitaireParam,
              datePeremption: datePeremptionParam);
          object.produit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.produit.attach(store);
          object.fournisseur.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.fournisseur.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Fournisseur] entity fields to define ObjectBox queries.
class Fournisseur_ {
  /// See [Fournisseur.id].
  static final id =
      obx.QueryIntegerProperty<Fournisseur>(_entities[0].properties[0]);

  /// See [Fournisseur.qr].
  static final qr =
      obx.QueryStringProperty<Fournisseur>(_entities[0].properties[1]);

  /// See [Fournisseur.nom].
  static final nom =
      obx.QueryStringProperty<Fournisseur>(_entities[0].properties[2]);

  /// See [Fournisseur.phone].
  static final phone =
      obx.QueryStringProperty<Fournisseur>(_entities[0].properties[3]);

  /// See [Fournisseur.adresse].
  static final adresse =
      obx.QueryStringProperty<Fournisseur>(_entities[0].properties[4]);

  /// See [Fournisseur.dateCreation].
  static final dateCreation =
      obx.QueryDateProperty<Fournisseur>(_entities[0].properties[5]);

  /// See [Fournisseur.derniereModification].
  static final derniereModification =
      obx.QueryDateProperty<Fournisseur>(_entities[0].properties[6]);

  /// See [Fournisseur.createdBy].
  static final createdBy =
      obx.QueryIntegerProperty<Fournisseur>(_entities[0].properties[7]);

  /// See [Fournisseur.updatedBy].
  static final updatedBy =
      obx.QueryIntegerProperty<Fournisseur>(_entities[0].properties[8]);

  /// See [Fournisseur.deletedBy].
  static final deletedBy =
      obx.QueryIntegerProperty<Fournisseur>(_entities[0].properties[9]);

  /// see [Fournisseur.produits]
  static final produits =
      obx.QueryRelationToMany<Fournisseur, Produit>(_entities[0].relations[0]);
}

/// [Produit] entity fields to define ObjectBox queries.
class Produit_ {
  /// See [Produit.id].
  static final id =
      obx.QueryIntegerProperty<Produit>(_entities[1].properties[0]);

  /// See [Produit.qr].
  static final qr =
      obx.QueryStringProperty<Produit>(_entities[1].properties[1]);

  /// See [Produit.image].
  static final image =
      obx.QueryStringProperty<Produit>(_entities[1].properties[2]);

  /// See [Produit.nom].
  static final nom =
      obx.QueryStringProperty<Produit>(_entities[1].properties[3]);

  /// See [Produit.description].
  static final description =
      obx.QueryStringProperty<Produit>(_entities[1].properties[4]);

  /// See [Produit.prixAchat].
  static final prixAchat =
      obx.QueryDoubleProperty<Produit>(_entities[1].properties[5]);

  /// See [Produit.prixVente].
  static final prixVente =
      obx.QueryDoubleProperty<Produit>(_entities[1].properties[6]);

  /// See [Produit.stock].
  static final stock =
      obx.QueryDoubleProperty<Produit>(_entities[1].properties[7]);

  /// See [Produit.stockUpdate].
  static final stockUpdate =
      obx.QueryDateProperty<Produit>(_entities[1].properties[8]);

  /// See [Produit.stockinit].
  static final stockinit =
      obx.QueryDoubleProperty<Produit>(_entities[1].properties[9]);

  /// See [Produit.dateCreation].
  static final dateCreation =
      obx.QueryDateProperty<Produit>(_entities[1].properties[10]);

  /// See [Produit.datePeremption].
  static final datePeremption =
      obx.QueryDateProperty<Produit>(_entities[1].properties[11]);

  /// See [Produit.derniereModification].
  static final derniereModification =
      obx.QueryDateProperty<Produit>(_entities[1].properties[12]);

  /// See [Produit.minimStock].
  static final minimStock =
      obx.QueryDoubleProperty<Produit>(_entities[1].properties[13]);

  /// See [Produit.origine].
  static final origine =
      obx.QueryStringProperty<Produit>(_entities[1].properties[14]);

  /// See [Produit.createdBy].
  static final createdBy =
      obx.QueryIntegerProperty<Produit>(_entities[1].properties[15]);

  /// See [Produit.updatedBy].
  static final updatedBy =
      obx.QueryIntegerProperty<Produit>(_entities[1].properties[16]);

  /// See [Produit.deletedBy].
  static final deletedBy =
      obx.QueryIntegerProperty<Produit>(_entities[1].properties[17]);

  /// See [Produit.alertPeremption].
  static final alertPeremption =
      obx.QueryIntegerProperty<Produit>(_entities[1].properties[18]);

  /// see [Produit.approvisionnements]
  static final approvisionnements =
      obx.QueryBacklinkToMany<Approvisionnement, Produit>(
          Approvisionnement_.produit);
}

/// [Client] entity fields to define ObjectBox queries.
class Client_ {
  /// See [Client.id].
  static final id =
      obx.QueryIntegerProperty<Client>(_entities[2].properties[0]);

  /// See [Client.qr].
  static final qr = obx.QueryStringProperty<Client>(_entities[2].properties[1]);

  /// See [Client.nom].
  static final nom =
      obx.QueryStringProperty<Client>(_entities[2].properties[2]);

  /// See [Client.phone].
  static final phone =
      obx.QueryStringProperty<Client>(_entities[2].properties[3]);

  /// See [Client.adresse].
  static final adresse =
      obx.QueryStringProperty<Client>(_entities[2].properties[4]);

  /// See [Client.description].
  static final description =
      obx.QueryStringProperty<Client>(_entities[2].properties[5]);

  /// See [Client.dateCreation].
  static final dateCreation =
      obx.QueryDateProperty<Client>(_entities[2].properties[6]);

  /// See [Client.derniereModification].
  static final derniereModification =
      obx.QueryDateProperty<Client>(_entities[2].properties[7]);

  /// See [Client.createdBy].
  static final createdBy =
      obx.QueryIntegerProperty<Client>(_entities[2].properties[8]);

  /// See [Client.updatedBy].
  static final updatedBy =
      obx.QueryIntegerProperty<Client>(_entities[2].properties[9]);

  /// See [Client.deletedBy].
  static final deletedBy =
      obx.QueryIntegerProperty<Client>(_entities[2].properties[10]);

  /// see [Client.factures]
  static final factures =
      obx.QueryBacklinkToMany<Facture, Client>(Facture_.client);
}

/// [Facture] entity fields to define ObjectBox queries.
class Facture_ {
  /// See [Facture.id].
  static final id =
      obx.QueryIntegerProperty<Facture>(_entities[3].properties[0]);

  /// See [Facture.qr].
  static final qr =
      obx.QueryStringProperty<Facture>(_entities[3].properties[1]);

  /// See [Facture.date].
  static final date =
      obx.QueryDateProperty<Facture>(_entities[3].properties[2]);

  /// See [Facture.client].
  static final client =
      obx.QueryRelationToOne<Facture, Client>(_entities[3].properties[3]);

  /// See [Facture.createdBy].
  static final createdBy =
      obx.QueryIntegerProperty<Facture>(_entities[3].properties[4]);

  /// See [Facture.updatedBy].
  static final updatedBy =
      obx.QueryIntegerProperty<Facture>(_entities[3].properties[5]);

  /// See [Facture.deletedBy].
  static final deletedBy =
      obx.QueryIntegerProperty<Facture>(_entities[3].properties[6]);

  /// See [Facture.impayer].
  static final impayer =
      obx.QueryDoubleProperty<Facture>(_entities[3].properties[7]);

  /// see [Facture.lignesFacture]
  static final lignesFacture =
      obx.QueryBacklinkToMany<LigneFacture, Facture>(LigneFacture_.facture);
}

/// [LigneFacture] entity fields to define ObjectBox queries.
class LigneFacture_ {
  /// See [LigneFacture.id].
  static final id =
      obx.QueryIntegerProperty<LigneFacture>(_entities[4].properties[0]);

  /// See [LigneFacture.produit].
  static final produit =
      obx.QueryRelationToOne<LigneFacture, Produit>(_entities[4].properties[1]);

  /// See [LigneFacture.facture].
  static final facture =
      obx.QueryRelationToOne<LigneFacture, Facture>(_entities[4].properties[2]);

  /// See [LigneFacture.quantite].
  static final quantite =
      obx.QueryDoubleProperty<LigneFacture>(_entities[4].properties[3]);

  /// See [LigneFacture.prixUnitaire].
  static final prixUnitaire =
      obx.QueryDoubleProperty<LigneFacture>(_entities[4].properties[4]);
}

/// [DeletedProduct] entity fields to define ObjectBox queries.
class DeletedProduct_ {
  /// See [DeletedProduct.id].
  static final id =
      obx.QueryIntegerProperty<DeletedProduct>(_entities[5].properties[0]);

  /// See [DeletedProduct.name].
  static final name =
      obx.QueryStringProperty<DeletedProduct>(_entities[5].properties[1]);

  /// See [DeletedProduct.description].
  static final description =
      obx.QueryStringProperty<DeletedProduct>(_entities[5].properties[2]);

  /// See [DeletedProduct.price].
  static final price =
      obx.QueryDoubleProperty<DeletedProduct>(_entities[5].properties[3]);

  /// See [DeletedProduct.quantity].
  static final quantity =
      obx.QueryIntegerProperty<DeletedProduct>(_entities[5].properties[4]);

  /// See [DeletedProduct.createdBy].
  static final createdBy =
      obx.QueryIntegerProperty<DeletedProduct>(_entities[5].properties[5]);

  /// See [DeletedProduct.updatedBy].
  static final updatedBy =
      obx.QueryIntegerProperty<DeletedProduct>(_entities[5].properties[6]);

  /// See [DeletedProduct.deletedBy].
  static final deletedBy =
      obx.QueryIntegerProperty<DeletedProduct>(_entities[5].properties[7]);

  /// See [DeletedProduct.deletedAt].
  static final deletedAt =
      obx.QueryDateProperty<DeletedProduct>(_entities[5].properties[8]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.id].
  static final id = obx.QueryIntegerProperty<User>(_entities[6].properties[0]);

  /// See [User.photo].
  static final photo =
      obx.QueryStringProperty<User>(_entities[6].properties[1]);

  /// See [User.username].
  static final username =
      obx.QueryStringProperty<User>(_entities[6].properties[2]);

  /// See [User.password].
  static final password =
      obx.QueryStringProperty<User>(_entities[6].properties[3]);

  /// See [User.email].
  static final email =
      obx.QueryStringProperty<User>(_entities[6].properties[4]);

  /// See [User.phone].
  static final phone =
      obx.QueryStringProperty<User>(_entities[6].properties[5]);

  /// See [User.role].
  static final role = obx.QueryStringProperty<User>(_entities[6].properties[6]);
}

/// [Approvisionnement] entity fields to define ObjectBox queries.
class Approvisionnement_ {
  /// See [Approvisionnement.id].
  static final id =
      obx.QueryIntegerProperty<Approvisionnement>(_entities[7].properties[0]);

  /// See [Approvisionnement.quantite].
  static final quantite =
      obx.QueryDoubleProperty<Approvisionnement>(_entities[7].properties[1]);

  /// See [Approvisionnement.prixUnitaire].
  static final prixUnitaire =
      obx.QueryDoubleProperty<Approvisionnement>(_entities[7].properties[2]);

  /// See [Approvisionnement.datePeremption].
  static final datePeremption =
      obx.QueryDateProperty<Approvisionnement>(_entities[7].properties[3]);

  /// See [Approvisionnement.produit].
  static final produit = obx.QueryRelationToOne<Approvisionnement, Produit>(
      _entities[7].properties[4]);

  /// See [Approvisionnement.fournisseur].
  static final fournisseur =
      obx.QueryRelationToOne<Approvisionnement, Fournisseur>(
          _entities[7].properties[5]);
}
